### ISSUE TITLE
Please add Request Object instead of basic url string

### ISSUE THREAD

**Issue by mrfatboy** [datMaffin/homebridge-http-slider#2]
Hello,
I was looking for a http slider plugin for homebridge and came across yours.  It's 99% what I need. I want to control my Yamaha AVR volume.  To control the Yamaha AVR's volume I need to send a POST Request with XML Body plain/text.

An Example:
                {
                    "method": "POST",
                    "url": "http://192.168.1.20:80/YamahaRemoteControl/ctrl",
                    "body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><YAMAHA_AV cmd=\"PUT\"><Main_Zone><Volume><Lvl><Val>-150</Val><Exp>1</Exp><Unit>dB</Unit></Lvl></Volume></Main_Zone></YAMAHA_AV>"
                }

The above Request sets the volume level to -150db.  I would like to have a list of them (say 10) for a slider with volume setting 1-10.

Does your plugin support a list of Request object like the one above?  If not, could you add the feature?  It would be a big help to me.

Thanks.

**Comment by datMaffin** [comment]
Sorry for the commit spam. (bash does some weird stuff, additionally I already had to fix a bug.).

All changes can be found in e8843f0. I also updated the [README](https://github.com/datMaffin/homebridge-http-slider/blob/request_objects/README.md) with relevant `config` information.
***I did not test this code.** (I did not have a homebridge testing environment + mock server available/did not really want to set them up right now.)*

Installing should be possible via `npm -g install datMaffin/homebridge-http-slider#request_objects`

I do not really plan on merging the request_objects branch to master. Feel free to fork ;)

**Comment by mrfatboy** [comment]
Thanks!  However, I am getting the following error when I try to install. Am I doing something incorrectly?


C:\Users\acer>npm -g install datMaffin/homebridge-http-slider#request_objects
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/datMaffin/homebri
dge-http-slider.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\acer\AppData\Roaming\npm-cache\_logs\2020-11-05T21_55_45_5
20Z-debug.log

C:\Users\acer>

**Comment by datMaffin** [comment]
hm.. do you have git installed?

The error seems to be Windows specific..

**Comment by mrfatboy** [comment]
Doh!  Not on my windows 10 htpc where Homebridge resides.  I am actually teamviewing in from my main windows 10 machine.  Is there another way to install? Or I will install git on the htpc.  It's a tiny little thing :)

**Comment by datMaffin** [comment]
The install did work for me when executed in the Windows  "git bash".

**Comment by mrfatboy** [comment]
I'm rusty.  I set all of this stuff up 7 years ago on my main computer and never looked back.  :)  I will try to get git bash on the htpc.

**Comment by mrfatboy** [comment]
I got everything installed.  The fan button shows up on my iphone. But I am getting "no response" on the button.  I get the following error in Homebridge status window.

Suggestions?

[11/5/2020, 2:50:41 PM] ReferenceError: callhttp is not defined
    at Timeout._onTimeout (C:\Users\acer\AppData\Roaming\npm\node_modules\homebridge-http-slider\index.js:204:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[11/5/2020, 2:50:41 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[11/5/2020, 2:50:46 PM]

**Comment by datMaffin** [comment]
Ok, this error should be fixed now.
The plugin can be updated by just installing it again (`npm -g install datMaffin/homebridge-http-slider#request_objects`)

**Comment by mrfatboy** [comment]
Fantastic! Great job!  Works perfectly! Thank you so much!

Now!! :)  Do you have time to put the cherry on top? :)

Could you add an "onurl" and "offurl" request objects.  That way you can turn the device ON or OFF with the button and then control with the slider.  For example, turning ON/OFF a stereo/AVR and then controlling volume.

The "onUrl" and "offUrl" could also be a list of request objects.  See Multiple ON/OFF urls format here. Scroll down.

https://github.com/Supereg/homebridge-http-switch

It would be awesome if you could make the modification if you have time.

Thanks again


          "onUrl": {
            "url": "http://localhost/api/switchOn",
            "method": "GET"
             "body": "text",
          },
          "offUrl": {
            "url": "http://localhost/api/switchOff",
            "method": "GET"
             "body": "text",
          },

**Comment by datMaffin** [comment]
No problem.

---
Your proposal does not seem to fit in the scope of this project.

(Admittedly, I do not quite understand what you want. It sounds like you could just use homebridge-http-switch.)

**Comment by mrfatboy** [comment]
Currently,   
  

  
The your slider switch only slides and is always on in the Home app.   
  

  
It would be nice if you tap the button and it triggers the button GUI    on and off. While executing the urlOn and urlOff request objects respectively. Long press opens up the slider and executes the httpstates request object list. Basically just like a normal fan slider switch.   
  

  
I am using the http-switch plug-in also and I don’t believe they had slider capability. That’s why I found your plug-in. Did I miss something?
  

  
Did I explain it better?
  

  
Let me know.   
  
Thanks
  
M
  

  

  
  
  
    
  

  
  
>

**Comment by datMaffin** [comment]
I think I did understand your request. See #3.
> Ok, an on/off button that would be _interacting_ with the slider (activating/deactivating it)

Definitely not trivial. (Adding request objects was trivial.)

I like the idea and created an issue. Working on it has a pretty low priority though; i.e. very unlikely to be worked on during the next few months.

**Comment by mrfatboy** [comment]
Thanks. That would great to add when you have time.   
  
  
  
    
  

  
  
>
